### ISSUE TITLE
Generic Token Locker

### ISSUE THREAD

**Issue by ilblackdragon** [near/rainbow-bridge-cli#126]
Token locker allows to mint/burn erc20s on NEAR and lock/unlock nep21s from NEAR side for sending to Ethereum.

Specifically:
 - [ ] Factory contract that will create new nep21 contract when new erc20 is locked (this should require extra fee and allows to name the contract: e.g. `dai.bridge.near`)
     Specialized nep21 that allows:
      - minting by factory / "owner"
      - burning by factory / "owner"
 - [ ] Accepts nep21s transfers to it and can either: 
     - If the token type is under this factory, send burn action to the factory and record that receipt result for Ethereum
     - Otherwise if it's some other kind of nep21: "lock" it
  - [ ] Accepts "bridge" events and depending on type:
     - If the token type is under this factory, mint for given address
     - If the token type is not, transfers funds on that nep21

Consideration: we don't need to burn erc20 tokens on NEAR side on return, we can just keep them in the locker. Then it can be unlocked back vs minted if there are extra balance. This would require more logic on fungible token side.

Suggestion for the naming of NEAR connector contracts:
  - <hex(eth_address)>.<factory_account_id>)

Ethereum address is 20 bytes, which is 40 characters in hex, which makes factory name to go up to 24 characters.

PS. This has a counter-party generic ERC-20 token locker on Ethereum side. It allows to lock any ERC-20 and maintains it until this token locker doesn't provide unlock event. For NEP-21s to bridge to the other side, token locker works as a factory and deploys new ERC-20 with mint/burn functionality (mirroring functionality here).

# Contract specifications

## Ethereum's side

```solidity
contract ERC20Locker {
  constructor(bytes memory nearTokenFactory, INearProver prover) public;
  function lockToken(IERC20 token, uint256 amount, string memory accountId) public;
  function unlockToken(bytes memory proofData, uint64 proofBlockHeader) public;
}
```

## NEAR's side

```rust
struct BridgeTokenFactory {
    tokens: UnorderedMap<EvmAddress, AccountId>;
}

impl BridgeTokenFactory {
  /// Relays the lock event from Ethereum.
  /// If given token doesn't exist yet in `tokens` map, create new one
  /// Name will be <hex(evm_address)>.<current_id>
  /// Send `mint` action to that token.
  pub fn deposit();
  
  /// Withdraws funds from NEAR to Ethereum.
  /// This will burn the token in the appropriate BridgeToken contract.
  /// And create an event for Ethereum to unlock the token.
  pub fn withdraw(token_account: AccountId, amount: Balance, recipient: EvmAddress);

  // Deploys BridgeToken contract to the given address.
  fn deploy_bridge_token(account_id: AccountId);
}

struct BridgeToken {
   controller: AccountId;
   token: Token; // uses https://github.com/ilblackdragon/balancer-near/tree/master/near-lib-rs
}

impl BridgeToken {
   pub fn new(controller: AccountId) -> Self {
       Self { controller, token: Token::new() }
   }

   pub fn mint(account_id: AccountId, amount: Balance) {
       assert_eq!(env::predecessor_id(), self.controller, "Only controller is allowed to mint the tokens");
       self.token.mint(account_id, amount);
   }

   pub fn burn(account_id: AccountId, amount: Balance) {
       assert_eq!(env::predecessor_id(), self.controller, "Only controller is allowed to mint the tokens");
       self.token.burn(account_id, amount);
   }
}

impl FungibleToken for BridgeToken {
   ... // see example https://github.com/ilblackdragon/balancer-near/blob/master/balancer-pool/src/lib.rs#L329
}
```

**Comment by Kouprin** [comment]
We use rainbow-token-connector since https://github.com/near/rainbow-bridge-cli/pull/347 is merged. Reopen it if there is something unfinished.
