### ISSUE TITLE
Resuming transfer commands

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge-cli#145]
`transfer-eth-erc20-to-near` and `transfer-eth-erc20-from-near` should be resumable. In production setting they will take long time to execute (minutes or hours) because they will be waiting for the blocks to be submitted or become valid. During this time the command can be accidentally or purposefully terminated. After such termination it should be possible to resume the transfer. We need to complete two things to achieve this:
* Transfer commands need to log in high detail every transaction they execute, so that if transfer is terminated in a random spot it can be resumed manually by reading through logs;
* The most common spot for termination would be when command is waiting for blocks. Before transfer starts waiting for the blocks it should print into stdout arguments that can be used to resume this command if it terminates.

**Comment by ailisp** [comment]
transfer-eth-erc20-to-near is done in #188 , if this approach looks good i'll also use similar for transfer-eth-erc20-from-near

**Comment by ailisp** [comment]
This is done in rainbow-bridge-lib
