### ISSUE TITLE
Fuzz test different merkle paths in Near2EthProver

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge-cli#201]
We need to unit tests the code that verifies merkle paths by generating various merkle paths in various merkle tries.

**Comment by nearmax** [comment]
Duplicate with another issue?

**Comment by ailisp** [comment]
> Duplicate with another issue?

Seems not

**Comment by ailisp** [comment]
@nearmax equivalent test in nearcore side is not very comprehensive with lots of fuzzing, is that good enough? https://github.com/nearprotocol/nearcore/blob/master/core/primitives/src/merkle.rs#L178

If so i'll just test same in solidity. Otherwise we should add fuzz test on both
