### ISSUE TITLE
[Medium] The challenge period is too short

### ISSUE THREAD

**Issue by ailisp** [near/rainbow-bridge-cli#246]
As reported by a third party:

An attacker can potentially submit a fake block and try to steal all the funds from the bridge. To protect the funds, there is a time period (4 hours) to challenge the invalid block.

That means that someone should be monitoring the Bridge activity continuously. Additionally, the attacker can try to congest Ethereum, so it would be hard to execute the transaction. Currently, NEAR is going to monitor the bridge with their watchdog system. Also, there is no direct incentive for other participants to monitor the bridge constantly because invalid blocks are not meant to occur. So if the watchdog is offline for any reason, or NEAR becomes malicious, 4 hours may not be enough for everyone to notice the attack and react.

Recommendation
-----------------
Just increasing challenge time will not be beneficial because, with the current architecture, this time should be at least shorter than the NEAR epoch duration. The option could be to allow submitting new blocks before the last provided block is considered valid.

**Comment by ailisp** [comment]
All epochs, or at least recent N last epoch info need to be stored, to challenge/revert a block in last N-1 epochs, instead of current 1 epoch. That need some rewrite. Current testnet epoch is 12 hour, we can challenge a block as early as the second early block in last epoch, so the alternative can we extend 4 hour to 10 hour without much change, which one do we consider better?

**Comment by nearmax** [comment]
We asked a question why we cannot overcome the congestion by exponentially increasing the gas price of the transaction. The explanation was that someone might be front-running every single challenge by submitting their own challenge and immediately resubmitting a different broken block. This will however reset the time on the block, which means that they would need to do it forever.

**Comment by nearmax** [comment]
Closing this issue, since it was acknowledged.
