### ISSUE TITLE
Extract RainbowLib

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge-cli#297]
We need to extract RainbowLib from the current CLI code and make CLI just a thin wrapper around rainbowlib.

We might need to do it in several steps, since we cannot extract the code that uses ethashproof Go tool, because this library is going to be used potentially from the browser.

Initial APIs should be provided for app developer usage:
 - Initiate "transfer" from Ethereum (e.g. 1st step of bridge transaction)
 - Initiate "transfer" from NEAR (e.g. 1st step of bridge transaction)
 - Monitor state of the "transfer" - should expose a state machine of the transfer. State can be described:
    - Waiting for transaction (transaction is not included yet)
    - Tx included in the block (Ethereum or NEAR)
    - Block relayed to the other chain
        - Report number of confirmations relayed so far for Ethereum blocks
        - Report number of blocks to wait to consider block not challenged for NEAR blocks
    - Ready: tx ready for 2nd step

Second milestone of APIs:
 - For Eth -> NEAR, extract EventLog from Eth for given tx, transform into Proof 
 - Initiate "mint" / "unlock" on NEAR for given proof (e.g. 2nd step of bridge transaction)
 - For NEAR -> Eth, extract Receipt's for given tx and and transform into Proof
 - Initiate "unlock" / "mint" on Ethereum for given proof (e.g. 2nd step of bridge transaction) 

Third milestone:
 - Expose block relayer functionality
      - This is easy for NEAR -> Ethereum, but Ethereum -> NEAR requires Go module which can not be used inside a pure library like this (pure == can be imported in browser)

**Comment by ailisp** [comment]
> We need to extract RainbowLib from the current CLI code and make CLI just a thin wrapper around rainbowlib.

I think currently you can import rainbow-bridge-cli as a lib, in another nodejs source code. And cli is importing lib/commands and execute.  What is needed in this issue?

> since we cannot extract the code that uses ethashproof Go tool, because this library is going to be used potentially from the browser.

We can consider compile that lib to wasm, if it didn't work well, work on #150 and compile that to wasm

**Comment by nearmax** [comment]
@Kouprin Is it done, should we close it?

**Comment by Kouprin** [comment]
> @Kouprin Is it done, should we close it?

The only initial step is done. We need to work closely with @chadoh and @ilblackdragon to build reasonable API for frontend developers.

I suggest to close this task and to open a set of relevant tasks at https://github.com/near/rainbow-bridge-lib repo.

**Comment by Kouprin** [comment]
All next steps will be discussed in https://github.com/near/rainbow-bridge-lib/issues/2
