### ISSUE TITLE
Fix incorrect version bump

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge-cli#358]
We broke rainbow bridge by incorrectly bumping semver in here: https://github.com/near/rainbow-bridge-cli/pull/342 This was a non-backwards compatible API change which should’ve resulted in major version bump, instead we bumped the patch. 

For all repos we need to do the following:
* [x] Publish new patch version that reverts token factory and any API-breaking changes;
* [ ] Publish new major version with token factory changes.

**Comment by nearmax** [comment]
Please also add changelog file like we do here: https://github.com/nearprotocol/nearcore/blob/master/runtime/CHANGELOG.md

**Comment by ailisp** [comment]
make it P1, as @chadoh and me published new patch version that should unblock hackathon now

**Comment by nearmax** [comment]
While addressing https://github.com/near/rainbow-bridge-cli/issues/358 which requires releasing new version of the bridge before the token factory,  https://github.com/near/rainbow-bridge-sol/ was incorrectly reverted. https://github.com/near/rainbow-bridge-sol/commit/2eb39c543d26370fea6f77f17607e0c4772e4979 does not add token locker contract back.

**Comment by nearmax** [comment]
Please make sure that everything works before publishing the version, but executing commands here: https://github.com/near/rainbow-bridge-cli#using-bridge-on-testnet and https://github.com/near/rainbow-bridge-cli#deploying-and-using-locally
