### ISSUE TITLE
Migration instructions to token factory

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge-cli#361]
Our current hackathon participants have projects that assume that token connectors are not factories. With the introduction of factory token connectors they would have to update their code. We need to write a migration guideline and add it into changelog proposed here: https://github.com/near/rainbow-bridge-cli/issues/358#issuecomment-701529790

**Comment by ailisp** [comment]
Current token connector based instruction is already on master branch, and #360 has provide an upgrading config if they need to switch to rainbow bridge 2.0 (with token connector and factory)

**Comment by nearmax** [comment]
We need instructions for users who depend directly on the contracts and want to migrate their JS code. These instructions need to explain how interface has changed, and how they need to update their code.
